### ISSUE TITLE
Compatibility with Bitbucket Pipelines security features

### ISSUE THREAD

**Issue by andrewodri** [amazonlinux/container-images#16]
When using `amazonlinux:1` or `amazonlinux:2018.03` in Bitbucket Pipelines as a host container to build a Docker image based off `amazonlinux:1` of `amazonlinux:2018.03`, the following error occurs:

```
Failed:
iputils.x86_64 0:20121221-7.13.amzn1 
```

This can be reproduced with the following `Dockerfile` and `bitbucket-pipelines.yml` file:

_Dockerfile_
```
FROM amazonlinux:1

RUN yum -y update && yum -y install iputils
```

_bitbucket-pipelines.yml_
```
clone:
  depth: 1

options:
  docker: true

pipelines:
  tags:
    build:
      - step:
          name: Build
          image: amazonlinux:1
          caches:
            - docker
          script:
            - docker build --tag organization/repo:tag .
```

This appears to be associated with an update to Pipelines enabling user namespace remapping: https://confluence.atlassian.com/bitbucket/infrastructure-changes-in-bitbucket-pipelines-872135046.html#InfrastructurechangesinBitbucketPipelines-September2018-DockerinDockerUserNamespaceRemapping

The was confirmed by excluding user namespace remapping from my account, and performing a successful build from an identical `Dockerfile` and `bitbucket-pipelines.yml`.

Please see the following correspondence from Atlassian for addtional information on the issue:

> Hi Andrew,
> 
> Thank you for your ongoing patience while we look into this issue.
> Based on our observation, we notice that there’s a mounted directory (it’s the amazonlinux image) that is outside of the valid UID/GID range and some packages that get installed need to go into that directory.
> 
> With the user namespace feature enabled on the docker daemon, it stopped the build from proceeding with the "iputils-20121221-7.13.amzn1.x86_64" installation process.
> 
> Since this is a public docker image, we would suggest raising an issue with the maintainees to deploy a fix for it.
> https://hub.docker.com/_/amazonlinux/
> While waiting for the fix, we would also suggest either look for other docker image or creating a new docker image that suits your build.
> Use Docker images as build environments - Atlassian Documentation
> Solved: How do I create a docker image for Bitbucket Pipel...
> 
> As of now, we can whitelist your account so that you can continue with your build but we would suggest watching the following page for future updates from our team in regards to it:
> https://confluence.atlassian.com/bitbucket/infrastructure-changes-in-bitbucket-pipelines-872135046.html
