### ISSUE TITLE
Systems Manager Greengrass IOT Core Container

### ISSUE THREAD

**Issue by MaxOrelus** [amazonlinux/container-images#82]
Hi,

I'm using greengrass-core `2.5.3` the docker container version -- which utilizes `amazonlinux:2`. I'm deploying a IOT Thing, which will be using the following IOT Components

- [x] IOT Defender
- [x] Secrets Manager
- [x] Greengrass CLI
- [ ] Systems Manager Agent

All but Systems Manager Agent installs successfully. Is it feasible to launch Systems Manager Agent successfully from a greengrass-core docker container?

Is there host volumes that need to be attached so that SMA has the ability to do all the functionality it requires (systemctl, etc)?

How to allow systemctl within the greengrass-core docker container using `amazonlinux:2`?

```
version: '3.7'

services:
  greengrass:
    init: true
    privileged: true
    container_name: aws-iot-greengrass
    restart: unless-stopped
    image: aws-iot-greengrass:2.5.3
    environment:
      - COMPONENT_DEFAULT_USER=root
      - AWS_REGION=us-east-1
      - PROVISION=true
      - THING_GROUP_NAME=thing001
      - TES_ROLE_NAME=GreengrassV2TokenExchangeRole
      - TES_ROLE_ALIAS_NAME=GreengrassCoreTokenExchangeRoleAlias
      - DEPLOY_DEV_TOOLS=true
    ports:
      - 8883:8883
    volumes:
      # the Unix socket the Docker daemon listens on -- binded from host machine
      - /var/run/docker.sock:/var/run/docker.sock
      # Systems Manager Agent (maybe)
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
   ```
